// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1rc5NbcB71pMTMRryQVQyimKbsn1XFHs',
    appId: '1:855278908118:web:7a1297ac468e5257090f77',
    messagingSenderId: '855278908118',
    projectId: 'safify-7973d',
    authDomain: 'safify-7973d.firebaseapp.com',
    storageBucket: 'safify-7973d.appspot.com',
    measurementId: 'G-1GY38EZPN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIh4cWRgMLFfsZQaiPBStLT8kzyMt89Rg',
    appId: '1:855278908118:android:b1ec327af3b35d59090f77',
    messagingSenderId: '855278908118',
    projectId: 'safify-7973d',
    storageBucket: 'safify-7973d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk0DgR0E22c22cKDtZqwfSCfYnJFJqF-Y',
    appId: '1:855278908118:ios:3a6d8442de00fcd0090f77',
    messagingSenderId: '855278908118',
    projectId: 'safify-7973d',
    storageBucket: 'safify-7973d.appspot.com',
    iosBundleId: 'com.example.safify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk0DgR0E22c22cKDtZqwfSCfYnJFJqF-Y',
    appId: '1:855278908118:ios:3a6d8442de00fcd0090f77',
    messagingSenderId: '855278908118',
    projectId: 'safify-7973d',
    storageBucket: 'safify-7973d.appspot.com',
    iosBundleId: 'com.example.safify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1rc5NbcB71pMTMRryQVQyimKbsn1XFHs',
    appId: '1:855278908118:web:a43498f92ebf534a090f77',
    messagingSenderId: '855278908118',
    projectId: 'safify-7973d',
    authDomain: 'safify-7973d.firebaseapp.com',
    storageBucket: 'safify-7973d.appspot.com',
    measurementId: 'G-PC83Y172SD',
  );
}
